title: Whitley Secondary School
url: https://www.whitleysec.moe.edu.sg
favicon: /images/School_Logo.png
colors:
  primary-color: "#5b2c2c"
  secondary-color: "#f5a623"
  media-colors:
    - title: media-color-one
      color: "#5b2c2c"
    - title: media-color-two
      color: "#5b2c2c"
    - title: media-color-three
      color: "#5b2c2c"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: An Isomer site of the Whitley Secondary School
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d383uslwl5tysp.amplifyapp.com
prod: https://master.d383uslwl5tysp.amplifyapp.com
shareicon: /images/isomer-logo.svg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
